---
- name: intsalling packages
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: installing packages
      ansible.builtin.yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"
    
    - name: intsall httpd on ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: yes 
        state: latest
      when: ansible_os_family == "Debian"
    
    - name: starting httpd on ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    
    - name: starting httpd services
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
    
    - name: Copy file to remote machine
      ansible.builtin.copy:
        src: /home/ansadmin/playboks/index.html
        dest: /home/ansadmin/var/www/html/

